# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 684185cb3e5efa9623110fc960ab12a759863fae75c3b1366d908ace78fd16d26cd1f4fce626a2ae3d21c76b8b4676580b53bf4a70f8766ef6f88d09bab6111b

test:
  secret_key_base: bf69b15b7c09e6d4f37d6c1367102452763a0bb5d798c66a58656f89ddc65fabf2804c2afa717c7141d4f8ce0fdc411d558a3fbe15b5c826301b99e6bc689bc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
